baseURL = "https://status.example.com/"
languageCode = "ja"
title = "Server Status"

theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true